// DEPARTMENTS
export const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS';
export const GET_ALL_DEPARTMENTS_SUCCESS = 'GET_ALL_DEPARTMENTS_SUCCESS';
export const GET_ALL_DEPARTMENTS_FAILURE = 'GET_ALL_DEPARTMENTS_FAILURE';
export const SET_CURRENT_DEPARTMENT = 'SET_CURRENT_DEPARTMENT'

// CATEGORIES
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_FAILURE = 'GET_ALL_CATEGORIES_FAILURE';
export const SET_CATEGORY = 'SET_CATEGORY';

export const GET_CATEGORIES_BY_DEPARTMENT = 'GET_CATEGORIES_BY_DEPARTMENT';
export const GET_CATEGORIES_BY_SUCCESS = 'GET_CATEGORIES_BY_SUCCESS';
export const GET_CATEGORIES_BY_FAILURE = 'GET_CATEGORIES_BY_FAILURE'

// PRODUCTS
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE';
export const SET_PAGE = 'SET_PAGE';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_FAILURE = 'SEARCH_PRODUCT_FAILURE';
export const RESET_SEARCH = 'RESET_SEARCH';

export const GET_PRODUCTS_BY_DEPARTMENT = 'GET_PRODUCTS_BY_DEPARTMENT'
export const GET_PRODUCTS_BY_DEPARTMENT_SUCCESS = 'GET_PRODUCTS_BY_DEPARTMENT_SUCCESS';
export const GET_PRODUCTS_BY_DEPARTMENT_FAILURE = 'GET_PRODUCTS_BY_DEPARTMENT_FAILURE';

// CUSTOMERS
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_FAILURE = 'CREATE_CUSTOMER_FAILURE';

export const UPDATE_CUSTOMER_ADDRESS = 'UPDATE_CUSTOMER_ADDRESS';
export const UPDATE_CUSTOMER_ADDRESS_SUCCESS = 'UPDATE_CUSTOMER_ADDRESS_SUCCESS';
export const UPDATE_CUSTOMER_ADDRESS_FAILURE = 'UPDATE_CUSTOMER_ADDRESS_FAILURE';

export const LOGIN_CUSTOMER = 'LOGIN_CUSTOMER';
export const LOGIN_CUSTOMER_SUCCESS = 'LOGIN_CUSTOMER_SUCCESS';
export const LOGIN_CUSTOMER_FAILURE = 'CREATE_CUSTOMER_FAILURE';

export const LOGOUT_CUSTOMER = 'LOGOUT_CUSTOMER';

export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';

export const GET_PRODUCT_ATTRIBUTES = 'GET_PRODUCT_ATTRIBUTES';
export const GET_PRODUCT_ATTRIBUTES_SUCCESS = 'GET_PRODUCT_ATTRIBUTES_SUCCESS';
export const GET_PRODUCT_ATTRIBUTES_FAILURE = 'GET_PRODUCT_ATTRIBUTES_FAILURE';


// CART
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const INCREMENT_CART_ITEM_QUANTITY = 'INCREMENT_CART_ITEM_QUANTITY';
export const DECREMENT_CART_ITEM_QUANTITY = 'DECREMENT_CART_ITEM_QUANTITY';
export const UPDATE_CART_TOTAL = 'UPDATE_CART_TOTAL';
export const CLEAR_CART_ITEMS = 'CLEAR_CART_ITEMS';
export const MIGRATE_CART_ITEMS = 'MIGRATE_CART_ITEMS';
export const SAVE_UNIQUE_CART_ID = 'SAVE_UNIQUE_CART_ID';

export const GET_ALL_CUSTOMER_ORDERS = 'GET_ALL_CUSTOMER_ORDERS';
export const GET_ALL_CUSTOMER_ORDERS_SUCCESS = 'GET_ALL_CUSTOMER_ORDERS_SUCCESS';
export const GET_ALL_CUSTOMER_ORDERS_FAILURE = 'GET_ALL_CUSTOMER_ORDERS_FAILURE';

export const GET_ALL_SHIPPING_REGIONS_SUCCESS = 'GET_ALL_SHIPPING_REGIONS_SUCCESS';
export const GET_ALL_SHIPPING_REGIONS_FAILURE = 'GET_ALL_SHIPPING_REGIONS_FAILURE';
export const SET_SHIPPING_REGION_ID = 'SET_SHIPPING_REGION_ID';
export const SET_SHIPMENT_REGION_ID = 'SET_SHIPMENT_REGION_ID';

// SHIPMENTS
export const GET_SHIPPING_ID = 'GET_SHIPPING_ID';
export const GET_SHIPPING_ID_SUCCESS = 'GET_SHIPPING_ID_SUCCESS';
export const GET_SHIPPING_ID_FAILURE = 'GET_SHIPPING_ID_FAILURE';
export const SET_SHIPPING_ID = 'SET_SHIPPING_ID'


